version: '3'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: python3 tg_bot/bot.py

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
